### ISSUE TITLE
VirtualWindowShare is Missing in Csharp folder

### ISSUE THREAD

**Issue by andrewwasfy84** [Vidyo/vidyo.io-connector-wpf#3]
I'm not able to build the solution VirtualWindowShare  is missing. Please advise.

**Comment by vtareiev** [comment]
Andrew, I've just removed this file as it's obsolete and no longer used. Also I've added links to C# classes of the most recent Vidyo.io SDK v19.2.
Please pull on your side and let me know if it helps.
